In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

In [2]:
train = pd.read_csv("train2.csv")
test = pd.read_csv("test2.csv")

In [3]:
train.head()

Previous  Direction
0         1         -1
1        -1          1
2         1         -1
3        -1         -1
4        -1         -1

In [4]:
X_train = train.drop("Direction", axis=1)
X_train.head()

Previous
0         1
1        -1
2         1
3        -1
4        -1

In [5]:
y_train = train.drop("Previous", axis=1)
y_train.head()

Direction
0         -1
1          1
2         -1
3         -1
4         -1

In [6]:
X_test = test.drop("Direction", axis=1)
X_test.head()

Previous
0        -1
1         1
2         1
3         1
4         1

In [7]:
y_test = test.drop("Previous", axis=1)
y_test.head()

Direction
0          1
1          1
2          1
3          1
4         -1

Decision Tree

In [8]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [9]:
predictions = dtree.predict(X_test)
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

          -1       0.21      0.22      0.22        18
           1       0.36      0.35      0.36        23

    accuracy                           0.29        41
   macro avg       0.29      0.29      0.29        41
weighted avg       0.30      0.29      0.29        41



In [10]:
print(confusion_matrix(y_test,predictions))

[[ 4 14]
 [15  8]]


In [11]:
print(accuracy_score(y_test, predictions))

0.2926829268292683


Random Forest

In [12]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=10)
rfc.fit(X_train, y_train)

/Users/jasonswan/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [13]:
rfc_pred = rfc.predict(X_test)

In [14]:
print(classification_report(y_test,rfc_pred))

              precision    recall  f1-score   support

          -1       0.21      0.22      0.22        18
           1       0.36      0.35      0.36        23

    accuracy                           0.29        41
   macro avg       0.29      0.29      0.29        41
weighted avg       0.30      0.29      0.29        41



In [15]:
print(confusion_matrix(y_test,rfc_pred))

[[ 4 14]
 [15  8]]


In [16]:
print(accuracy_score(y_test, rfc_pred))

0.2926829268292683


Naive Bayes

In [17]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train,y_train)

/Users/jasonswan/opt/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [18]:
gnb_pred = gnb.predict(X_test)
print(classification_report(y_test,gnb_pred))

              precision    recall  f1-score   support

          -1       0.21      0.22      0.22        18
           1       0.36      0.35      0.36        23

    accuracy                           0.29        41
   macro avg       0.29      0.29      0.29        41
weighted avg       0.30      0.29      0.29        41



In [19]:
print(confusion_matrix(y_test,gnb_pred))

[[ 4 14]
 [15  8]]


In [20]:
print(accuracy_score(y_test, gnb_pred))

0.2926829268292683


SVM

In [21]:
from sklearn.svm import SVC
model = SVC()
model.fit(X_train,y_train)

/Users/jasonswan/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [22]:
predictions = model.predict(X_test)
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

          -1       0.21      0.22      0.22        18
           1       0.36      0.35      0.36        23

    accuracy                           0.29        41
   macro avg       0.29      0.29      0.29        41
weighted avg       0.30      0.29      0.29        41



In [23]:
print(confusion_matrix(y_test,predictions))

[[ 4 14]
 [15  8]]


In [24]:
print(accuracy_score(y_test, predictions))

0.2926829268292683


KNN

In [25]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train,y_train)
pred = knn.predict(X_test)

/Users/jasonswan/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


In [26]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

          -1       0.44      1.00      0.61        18
           1       0.00      0.00      0.00        23

    accuracy                           0.44        41
   macro avg       0.22      0.50      0.31        41
weighted avg       0.19      0.44      0.27        41



/Users/jasonswan/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [27]:
print(confusion_matrix(y_test,pred))

[[18  0]
 [23  0]]


In [28]:
print(accuracy_score(y_test,pred))

0.43902439024390244


Logistic Regression

In [29]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)

/Users/jasonswan/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [30]:
predictions = logmodel.predict(X_test)
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

          -1       0.21      0.22      0.22        18
           1       0.36      0.35      0.36        23

    accuracy                           0.29        41
   macro avg       0.29      0.29      0.29        41
weighted avg       0.30      0.29      0.29        41



In [31]:
print(confusion_matrix(y_test,predictions))

[[ 4 14]
 [15  8]]


In [32]:
print(accuracy_score(y_test, predictions))

0.2926829268292683


Decision Tree (With Bagging)

In [33]:
from sklearn.ensemble import BaggingClassifier
bag_clf = BaggingClassifier(
    DecisionTreeClassifier(), n_estimators=2500,
    max_samples=25, bootstrap=True, n_jobs=-1)
bag_clf.fit(X_train, y_train)

/Users/jasonswan/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/_bagging.py:645: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier(base_estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                        class_weight=None,
                                                        criterion='gini',
                                                        max_depth=None,
                                                        max_features=None,
                                                        max_leaf_nodes=None,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=1,
                                                        min_samples_split=2,
                                                        min_weight_fraction_leaf=0.0,
                                                        presort='deprecated',
                                                        random_state=None,


In [34]:
y_pred_bag = bag_clf.predict(X_test)

print(accuracy_score(y_test, y_pred_bag))

0.2926829268292683
